### PR TITLE
Added method to IUnleash that enables caller to provide runtime data.

### PR DESCRIPTION
**Pull request by royvandertuuk**
We would like to be able to pass properties to the IsEnabled method, so the strategies can act on these properties. Currently the only way to provide these properties is through the UnleashContext, but these values are initialized per request, and therefore not flexible enough for all scenario's.

### CODE REVIEW

**Review by stiano — COMMENTED** [review]
Thanks for you pull request, @royvandertuuk .

Any reason why we would need to clone the existing properties dictionary, and not just add to the existing one? And why not just overwrite existing items if they are already there in AppendProperties? Throwing an exception seems a bit rash here..
--> Properties[property.Key] = property.Value;

Could you please also add a test or two for this feature.

**Comment by royvandertuuk** [comment]
Thank you for your feedback @stiano.

Passing the properties in the IsEnabled method indicates that the properties should only be available in the scope of this method call. Adding these properties to the existing ones will also make these values available for all the IsEnabled calls that occur in the lifetime of the context instance that the properties were added to.

I throw an exception because I thought overriding the existing property could lead to unexpected behavior, but throwing an exception is a bit harsh. I will change this to replacing the value.

The tests in the solution are not being discovered (VS2017 and VS2019), therfore I had some difficulties adding tests. I will look into this and add the tests.

**Comment by stiano** [comment]
Thanks for the tests, @royvandertuuk.

I have to say that I still struggle to see good use cases for why context properties should only be valid inside the scope of a single method call. Is it a security concern for you? Could you please elaborate a bit more on this, please, with what kind of application/data etc? 

Before changing the public api of the library, I need to make sure that this is really necessary and makes sense for others as well.

**Comment by ivarconr** [comment]
> Before changing the public api of the library, I need to make sure that this is really necessary and makes sense for others as well.

I am curious about this as-well. My experience across the other client SDKs is that it has been sufficient to handle custom properties inside the context-provider. 

On the other hand it feels kind of elegant to be able to provide some just in time "context fields" and have these merged with the data from the context provider. And I guess the "custom properties" are good candidates for this. 

I might even adopt this to the other clients as well if it proves to make Unleash easier to use.

**Comment by royvandertuuk** [comment]
There are several use cases we have for this change:

1.	In a ASP.NET web API we have a category in our url, based on this category we want to have a feature enabled or disabled.
We could implement logic in our contextProvider that gets this category from the url, but ASP.NET Web API already provides attribute routing for this and supplies this data as parameter in our action.
If we implement this in the contextProvider, then we have duplicate code that is fragile. When we change the url in some way, the contextProvider needs to be changes as well.

Therefore we would rather use this:
```
[Route("entities/{category}/action")]
public ActionResult MyEntityAction(string category) 
{
	var isEnabled = _unleashClient.IsEnabled("specialFeature", new Dictionary<string, string> 
	{
		{ "category", category}
	});
	
	if(isEnabled)
	{
		//Do work..
	}
}
```
2.	Using posted values as input for strategies is another use case, we can go trough al posted values in our contextProvider and add specific values to our properties dictionary, but this creates the same issues.
We have to read the properties ourselves and cannot use the MVC model binding for this, and if the names of the posted values change we have to modify the contextProvider as well.
3.	We register the Unleash client in our dependency injection library as singleton, therefore our contextProvider needs to be singleton as well. This prevents us from using scoped classes in our contextProvider for setting our custom properties.
With the suggested change we can easily call the scoped classes and get the required data and set the appropriate properties.

**Comment by stiano** [comment]
Thanks @royvandertuuk. I can understand your reasons a bit clearer now. Your requirements "should" (haven`t tried) be possible with todays solution. As long as we save our unleashContext on the httpContext, it will be scoped to one request. Could you have a look?

```
public class MyUnleashContextProvider : IUnleashContextProvider
{
  private readonly IHttpContextAccessor httpContextAccessor;

  public MyUnleashContextProvider(IHttpContextAccessor httpContextAccessor)
  {
	 this.httpContextAccessor = httpContextAccessor;
  }

  public UnleashContext Context
  {
	 get
	 {
		var httpContext = httpContextAccessor.HttpContext;

		if (httpContext.Items[nameof(UnleashContext)] is UnleashContext unleashContext)
		{
		   return unleashContext;
		}
		else
		{
		   var newUnleashContext = new UnleashContext()
		   {
			  UserId = httpContext.User.Identity.Name,
			  // ...
		   };
		   httpContext.Items[nameof(UnleashContext)] = newUnleashContext;

		   return newUnleashContext;
		}
	 }
  }
}
```

```
public void ConfigureServices(IServiceCollection services)
{
   services.AddHttpContextAccessor();
   services.AddSingleton<MyUnleashContextProvider>();
   services.AddTransient<UnleashContext>(x =>
   {
	  var contextProvider = x.GetService<IUnleashContextProvider>();
	  return contextProvider.Context;
   });
   
   ...
}
```

```
public class MyCtrl : Controller
{
  private readonly IUnleash unleashClient;
  private readonly UnleashContext unleashContext;

  public Ctrl(IUnleash unleashClient, UnleashContext unleashContext)
  {
	 this.unleashClient = unleashClient;
	 this.unleashContext = unleashContext;
  }

  [Route("entities/{category}/action")]
  public ActionResult MyEntityAction(string category)
  {
	 // scoped for this user/request only
	 unleashContext.Properties.TryAdd("category", category);

	 var isEnabled = unleashClient.IsEnabled("specialFeature");

	 if (isEnabled)
	 {
		//Do work..
	 }
	 
	 unleashContext.Properties.Remove("category);
  }
}   
```

**Comment by royvandertuuk** [comment]
@stiano thank you for the example.
This would probably work, but I have some concerns about the given solution:

- UnleashContext is registered as transient, but in fact it is scoped, because you get the same context during the lifetime of a request. This could be circumvented by injecting the context provider into the controller and using the 'Context' property directly.
- Making the developer responsible for removing the properties is fragile and can cause security issues (see my example on an impersonation implementation below).

```
public class MyCtrl : Controller
{
  private readonly IUnleash unleashClient;
  private readonly UnleashContext unleashContext;

  public Ctrl(IUnleash unleashClient, UnleashContext unleashContext)
  {
	 this.unleashClient = unleashClient;
	 this.unleashContext = unleashContext;
  }

  [Route("work/ProcessQueue")]
  public ActionResult ProcessQueue()
  {
	  
	  var queue = GetQueue();
	  foreach(var queueItem in queue)
	  {
		// scoped for this user/request only
		unleashContext.UserId = queueItem.UserId;
	 
		var isEnabled = unleashClient.IsEnabled("specialFeature");

		 if (isEnabled)
		 {
			//Do work..
		 }
	  }
	
	   // Problem because the unleashContext.UserId is not set to the original system userId!	
	   // Feature evaluated based on last user from queue in stead of system user!
	  var feature2Enabled = unleashClient.IsEnabled("feature2");
  }	  
}
```

**Comment by stiano** [comment]
@royvandertuuk.

#1, I registered it as transient so the IOC would not cache it, and the api was cleaner, but your solution will of course work.

#2, The library is not designed to solve this problem out of the box, and your pull request does not solve it either (only context.Properties is affected). 

My hotfix would be a helper class like so:
```
   public class ContextProviderRollbackOnDispose : IDisposable
   {
      private readonly UnleashContext original;
      private readonly UnleashContext copy;

      public ContextProviderRollbackOnDispose(UnleashContext original)
      {
         this.original = original;
         this.copy = new UnleashContext()
         {
            UserId = original.UserId,
            RemoteAddress = original.RemoteAddress,
            SessionId = original.SessionId,
            Properties = original.Properties != null ? new Dictionary<string, string>(original.Properties) : null,
         };
      }

      public void Dispose()
      {
         // Revert back to original
         original.UserId = copy.UserId;
         original.RemoteAddress = copy.RemoteAddress;
         original.SessionId = copy.SessionId;
         original.Properties = copy.Properties != null ? new Dictionary<string, string>(copy.Properties) : null;
      }
   }
```
Which can be used like so:
```
      [Route("work/ProcessQueue")]
      public ActionResult ProcessQueue()
      {
         using (new ContextProviderRollbackOnDispose(unleashContext))
         {
            var queue = GetQueue();
            foreach (var queueItem in queue)
            {
               // scoped for this user/request only
               unleashContext.UserId = queueItem.UserId;

               var isEnabled = unleashClient.IsEnabled("specialFeature");

               if (isEnabled)
               {
                  //Do work..
               }
            }
         }
         
         // Feature evaluated based on system user
         var feature2Enabled = unleashClient.IsEnabled("feature2");
      }
```
I would probably have named it differently though :)

**Comment by royvandertuuk** [comment]
@stiano 

The pull request can be altered so it also solves the use case above.
But if i understand you correctly you are not inclined to support this in this library?

**Comment by stiano** [comment]
@royvandertuuk

That is correct. For now at least.  
And as far as I can understand, you are able to get on with your implementation in a fairly manageable way.

Thanks for your efforts for now.

**Comment by AroglDarthu** [comment]
Just chipping in some thoughts here...

As I see it, getting runtime values into `UnleashContext` seems like a very good idea. And sure, via elaborate ways you could 'manage' to poke these in with the current version. But why should it have to be so cumbersome?

I think the actual problem here is separation of concerns.
Why are these properties part of the static settings? It makes sense to separate these, at least up to the point where Unleash is actually called.

The `UnleashContextProvider` should provide a default context to the `UnleashSettings`. I would then opt for an overload of `IsEnabed` that just takes an `UnleashContext` instance. This runtime instance can then be merged with the default one.

This way the application can very easily provide the correct parameters for the strategies involved with the feature being queried.

Perhaps too, it should not be an `UnleashContext` exactly, but more an `IStrategyContext` of sorts, just to prevent overriding context properties that must remain const. It would also further show intent.

**Comment by stiano** [comment]
@AroglDarthu

Getting runtime values into UnleashContext for a regular web app with one user per request should actually be quite easy. Just register the UnleashContext into the container (as outlined above), inject it where you would like, and modify it as needed. In which situations will this not suit your needs?

If you want to create a pull request for your ideas we can of course discuss it.

**Pull request closed without merging**
